package com.smartscheduler.app.domain.model

import java.time.LocalDate
import java.time.LocalTime

/**
 * A fixed event imported from an ICS calendar file (e.g. class schedule).
 */
data class FixedEvent(
    val id: Long = 0,
    val title: String,
    val description: String = "",
    val location: String = "",
    val date: LocalDate,
    val startTime: LocalTime,
    val endTime: LocalTime,
    val recurrenceRule: String? = null
)

/**
 * A user-created to-do item with deadline and estimated duration.
 * estimatedMinutes = 0 means "unknown — let AI estimate".
 */
data class Todo(
    val id: Long = 0,
    val title: String,
    val description: String = "",
    val deadlineDate: LocalDate,
    val estimatedMinutes: Int = 0,  // 0 = AI will estimate
    val isCompleted: Boolean = false,
    val isDaily: Boolean = false,
    val createdAt: Long = System.currentTimeMillis()
)

/**
 * A time block generated by the AI scheduler.
 */
data class ScheduledBlock(
    val id: Long = 0,
    val todoId: Long? = null,
    val title: String,
    val date: LocalDate,
    val startTime: LocalTime,
    val endTime: LocalTime,
    val note: String = "",
    val generatedAt: Long = System.currentTimeMillis()
)

/**
 * Unified event type displayed on the timeline.
 */
data class TimelineEvent(
    val id: Long = 0,           // matches ScheduledBlock.id for SCHEDULED type
    val title: String,
    val date: LocalDate,
    val startTime: LocalTime,
    val endTime: LocalTime,
    val type: EventType,
    val description: String = "",
    val location: String = ""
)

enum class EventType {
    FIXED,      // from ICS import
    SCHEDULED   // AI-generated
}

/**
 * User settings for LLM configuration.
 */
data class LlmSettings(
    val baseUrl: String = "https://api.deepseek.com",
    val apiKey: String = "",
    val modelName: String = "deepseek-chat",
    val customPrompt: String = ""
)
